### ISSUE TITLE
link Form 1040

### ISSUE THREAD

**Issue by tonymorris** [chris-martin/haskell-libraries#1]
For those of us not in USA, to truly admire Qualified_Dividends_And_Capital_Gains_Worksheet.hs we need to see 2016 Form 1040.

I suggest linking it in the comments of the source file.

https://www.irs.gov/pub/irs-pdf/f1040.pdf

**Comment by chris-martin** [comment]
:+1: I'll link to https://www.irs.gov/pub/irs-prior/i1040gi--2016.pdf, foreigners need to see the full 106-page instruction book to understand the full glory of what's going on here.

**Comment by tonymorris** [comment]
haha nice

:+1:
