### ISSUE TITLE
(data-forest) Add "foldForest" catamorphism.

### ISSUE THREAD

**Issue by danidiaz** [chris-martin/haskell-libraries#2]
`Data.Tree` has a [`foldTree :: (a -> [b] -> b) -> Tree a -> b`](http://hackage.haskell.org/package/containers-0.5.10.2/docs/Data-Tree.html#v:foldTree) catamorphism, that consumes a tree in a more structured way than by using `Foldable` methods.

Analogously, perhaps it could be useful to implement a `foldForest` function.

I believe it would have type `foldForest :: ([(a,b)] -> b) -> Forest a -> b`.

**Comment by chris-martin** [comment]
Good idea! Done.

**Comment by chris-martin** [comment]
This is in version 0.1.0.4.
